version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose build
          cat $DOCKER_PASS | docker login https://docker.pkg.github.com -u julius88 --password-stdin
          docker-compose push